#!/bin/sh

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "--> Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  else
    echo "--> Homebrew already installed"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "--> Updating homebrew bundle"
    brew bundle --global
  fi

  # install --user common dependencies
  if command -v brew >/dev/null 2>&1; then
    echo "--> Installing common python dependencies"
    pip3 install -U pip
    pip3 install --user tox wheel
  fi

  if ! command -v poetry >/dev/null 2>&1; then
    echo "--> Installing Poetry package manager"
    curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python3
  fi

  if ! command -v nvm >/dev/null 2>&1; then
    echo "--> Installing nvm"
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
  fi

fi
